### ISSUE TITLE
100% of messages sent to iOS/APNS failing

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-AppEngine#40]
This started about 12 hours ago. 

Sample error log messages from apns.py:
sending notification with id:1327003522 to APNS failed: <class 'ssl.SSLError'>: [Errno 8] _ssl.c:529: EOF occurred in violation of protocol in 2th attempt, will wait 4 secs for next action

It retries for several attempts over the next minute and then fails returning code 500:
Traceback (most recent call last):
  File "/base/data/home/apps/s~safeslinger-messenger/01060000p.384392463242757969/postMessage.py", line 460, in main
    util.run_wsgi_app(application)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/webapp/util.py", line 101, in run_wsgi_app
    run_bare_wsgi_app(add_wsgi_middleware(application))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/webapp/util.py", line 119, in run_bare_wsgi_app
    result = application(env, _start_response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~safeslinger-messenger/01060000p.384392463242757969/postMessage.py", line 329, in post
    logging.error("Error: 500, Internal Server Error or APNS Unavailable. Our system failed. If this persists, contact support..")
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/logging/__init__.py", line 1585, in error
    root.error(msg, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/logging/__init__.py", line 1175, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/logging/__init__.py", line 1259, in _log
    fn, lno, func = self.findCaller()
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/logging/__init__.py", line 1226, in findCaller
    while hasattr(f, "f_code"):
DeadlineExceededError

**Comment by mwfarb** [comment]
At least Apple isn't reporting any system wide issues: https://developer.apple.com/system-status/

**Comment by mwfarb** [comment]
Diffing our version of apns.py and the current one at https://raw.githubusercontent.com/djacobs/PyAPNs/master/apns.py it seems like we may need an update.

**Comment by mwfarb** [comment]
The production and test versions are running the same code base, but the test instance is succeeding APNS, while production is failing. Hopefully the issue is an expired release push certificate and the new one can be obtained quickly.

**Comment by SafeSlingerProject** [comment]
Production certificate update has been uploaded and fixed.
